apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: emnwm8a3q-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: emnwm8a3q-go 
  name: emnwm8a3q-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: emnwm8a3q-go 
